# Generated by Django 4.0.5 on 2022-09-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/meter-reader-images/', verbose_name='meter image')),
                ('current_reading', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='current meter reading')),
                ('current_units', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='current units')),
                ('previous_month_reading', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='previous meter reading')),
                ('previous_month_units', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='previous month units')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tenant', verbose_name='tenant')),
            ],
        ),
    ]
