# Generated by Django 4.0.5 on 2022-09-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetotext',
            name='extracted_reading',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='meter reading'),
        ),
    ]
