# Generated by Django 4.0.5 on 2022-09-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverification'),
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityunit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant', verbose_name='tenant'),
        ),
    ]
