# Generated by Django 4.0.5 on 2022-09-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_ocr_remove_electricityunit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr',
            name='extracted_digits',
            field=models.DecimalField(decimal_places=1, default=12345.4, max_digits=7),
        ),
    ]
