# Generated by Django 4.0.5 on 2022-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_alter_imagetotext_extracted_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetotext',
            name='extracted_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='meter reading'),
        ),
    ]
