# Generated by Django 4.0.5 on 2022-09-06 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocr', '0003_alter_imagetotext_extracted_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/meter-reader-images/', verbose_name='meter image')),
                ('current_reading', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='current meter reading')),
                ('current_units', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='current units')),
                ('previous_month_reading', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='previous meter reading')),
                ('previous_month_units', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='previous month units')),
                ('payment_status', models.BooleanField(default=False)),
                ('total_payable_units', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageToText', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageToText',
        ),
    ]
