# Generated by Django 4.0.6 on 2022-07-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='fname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='lname',
        ),
    ]
