# Generated by Django 4.0.4 on 2022-07-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relns', '0002_alter_chat_receiver_alter_chat_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='VadaMaBasni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relns.owner')),
            ],
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
