# Generated by Django 4.0.4 on 2022-07-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relns', '0006_alter_tenant_owner_user_alter_owner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_tenant',
        ),
    ]
