# Generated by Django 4.0.5 on 2022-09-10 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_owner_is_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.FileField(upload_to='static/docs', verbose_name='citizenship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='rent amount')),
                ('internet_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('water_usage_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nagarpalika_fohr_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('electricity_rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='electricity charge per unit')),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='users.tenant')),
            ],
        ),
    ]
