# Generated by Django 4.0.5 on 2022-09-16 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.FileField(upload_to='static/docs', verbose_name='citizenship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='rent amount')),
                ('internet_price', models.IntegerField(default=0, verbose_name='Internet Price')),
                ('water_usage_price', models.IntegerField(verbose_name='water_usage_price')),
                ('nagarpalika_fohr_price', models.IntegerField(verbose_name='Nagarpalika Fohr Price')),
                ('electricity_rate', models.IntegerField(verbose_name='electricity charge per unit')),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='users.tenant', verbose_name='tenant_user')),
            ],
        ),
    ]
