# Generated by Django 4.0.5 on 2022-09-21 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 12, 20)),
        ),
    ]
