# Generated by Django 4.0.5 on 2022-09-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_owner_is_owner'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='users.tenant', verbose_name='tenant_user'),
        ),
    ]
