# Generated by Django 4.0.5 on 2022-09-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_agreement_electricity_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='electricity_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='electricity charge per unit'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='internet_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Internet Price'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='nagarpalika_fohr_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Nagarpalika Fohr Price'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='water_usage_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='water_usage_price'),
        ),
    ]
