# Generated by Django 4.0.5 on 2022-09-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_agreement_electricity_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='electricity_rate',
            field=models.IntegerField(verbose_name='electricity charge per unit'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='internet_price',
            field=models.IntegerField(default=0, verbose_name='Internet Price'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='nagarpalika_fohr_price',
            field=models.IntegerField(verbose_name='Nagarpalika Fohr Price'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='water_usage_price',
            field=models.IntegerField(verbose_name='water_usage_price'),
        ),
    ]
