# Generated by Django 4.0.5 on 2022-09-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='is_owner',
        ),
    ]
