# Generated by Django 4.0.5 on 2022-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
