# Generated by Django 4.0.5 on 2022-09-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('D', 'Deadline Approach'), ('S', 'Deadline Skipped'), ('C', 'Complaint'), ('P', 'Payment'), ('O', 'Other Payment'), ('A', 'Agreement Formed or Updated')], max_length=30, verbose_name='type of notification'),
        ),
    ]
