# Generated by Django 4.0.5 on 2022-09-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='deep_link',
            field=models.CharField(default='rentassist2021/api/notifications', max_length=70),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('D', 'Deadline Approach'), ('S', 'Deadline Skipped'), ('C', 'Complaint'), ('P', 'Payment'), ('O', 'Other Payment'), ('A', 'Agreement Formed'), ('CE', 'Contract Extended'), ('E', 'Contract Expiry'), ('CM', 'Configure Meter')], max_length=30, verbose_name='type of notification'),
        ),
    ]
