# Generated by Django 4.0.5 on 2022-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_deep_link_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('D', 'Deadline Approach'), ('S', 'Deadline Skipped'), ('C', 'Complaint'), ('T', 'Transaction'), ('A', 'Agreement Formed'), ('CE', 'Contract Extended'), ('E', 'Contract Expiry'), ('CM', 'Configure Meter')], max_length=30, verbose_name='type of notification'),
        ),
    ]
