# Generated by Django 4.0.5 on 2022-06-06 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=40, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='image',
            field=models.ImageField(blank=True, default='static/me.jpg', null=True, upload_to='static/owner-images/', verbose_name='image'),
        ),
    ]
