# Generated by Django 4.0.5 on 2022-07-07 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_alter_tenant_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tenant',
        ),
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=35, verbose_name='tenant name'),
            preserve_default=False,
        ),
    ]
