# Generated by Django 4.0.5 on 2022-09-20 01:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='rent amount')),
                ('internet_price', models.IntegerField(default=0, verbose_name='Internet Price')),
                ('water_usage_price', models.IntegerField(verbose_name='water_usage_price')),
                ('nagarpalika_fohr_price', models.IntegerField(verbose_name='Nagarpalika Fohr Price')),
                ('electricity_rate', models.IntegerField(verbose_name='electricity charge per unit')),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_owner', to='users.owner', verbose_name='owner user')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_month_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_to_be_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_paid_this_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='remaining amount')),
                ('status', models.CharField(choices=[('F', 'Fully Paid'), ('P', 'Partially Paid'), ('U', 'Unpaid')], max_length=25, verbose_name='payment status')),
                ('paid_at', models.DateField(auto_now=True)),
                ('next_payment_schedule', models.DateField(default=datetime.date(2022, 10, 20), verbose_name='next payment schedule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payer', to='users.tenant', verbose_name='who pays the rent')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/complains')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('urgency_level', models.CharField(choices=[('H', 'High'), ('I', 'Intermediate'), ('L', 'Low')], max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='users.tenant')),
            ],
        ),
    ]
