# Generated by Django 4.0.5 on 2022-09-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='Solved'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=200, verbose_name='Complaint Status'),
        ),
    ]
