# Generated by Django 4.0.5 on 2022-09-10 03:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_owner_is_owner'),
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='electricity_rate',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='internet_price',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='price',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='water_usage_price',
        ),
        migrations.AddField(
            model_name='rent',
            name='amount_paid_this_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rent',
            name='amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rent',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='remaining amount'),
        ),
        migrations.AddField(
            model_name='rent',
            name='next_payment_schedule',
            field=models.DateField(default=datetime.datetime(2022, 9, 10, 9, 44, 18, 414588)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='paid_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('FULL', 'Fully Paid'), ('PARTIAL', 'Partially Paid')], default='FULL', max_length=25, verbose_name='payment status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='this_month_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_payer', to='users.tenant', verbose_name='who pays the rent'),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
