# Generated by Django 4.0.5 on 2022-09-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_remove_transaction_tenant_delete_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='otherpayment',
            name='paid_by',
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Electricity',
        ),
        migrations.DeleteModel(
            name='OtherPayment',
        ),
    ]
