# Generated by Django 4.0.5 on 2022-09-10 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_alter_rent_amount_paid_this_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='next_payment_schedule',
            field=models.DateField(default=datetime.date(2022, 10, 10), verbose_name='next payment schedule'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('F', 'Fully Paid'), ('P', 'Partially Paid'), ('U', 'Unpaid')], max_length=25, verbose_name='payment status'),
        ),
    ]
