# Generated by Django 4.0.5 on 2022-09-11 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_alter_rent_next_payment_schedule_alter_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='next_payment_schedule',
            field=models.DateField(default=datetime.date(2022, 10, 11), verbose_name='next payment schedule'),
        ),
    ]
