# Generated by Django 4.0.5 on 2022-09-12 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0005_alter_rent_next_payment_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='next_payment_schedule',
            field=models.DateField(default=datetime.date(2022, 10, 12), verbose_name='next payment schedule'),
        ),
    ]
