# Generated by Django 4.0.5 on 2022-09-15 05:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverification'),
        ('rentapp', '0006_alter_rent_next_payment_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='next_payment_schedule',
            field=models.DateField(default=datetime.date(2022, 10, 15), verbose_name='next payment schedule'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payer', to='users.tenant', verbose_name='who pays the rent'),
        ),
    ]
