# Generated by Django 4.0.5 on 2022-09-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_token', models.CharField(max_length=50)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('CANCELLED', 'CANCELLED'), ('SUCCESS', 'SUCCESS')], max_length=20)),
                ('payment_response', models.JSONField(blank=True, null=True, verbose_name='Transaction response')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='users.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now=True, verbose_name='Paid At')),
                ('remarks', models.CharField(max_length=255, verbose_name='remarks')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_payment', to='users.tenant', verbose_name='Tenant')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
