# Generated by Django 4.0.5 on 2022-09-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayRent',
        ),
    ]
