# Generated by Django 4.0.5 on 2022-09-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_owner_is_owner'),
        ('payment', '0002_delete_payrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpayment',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Paid At'),
        ),
        migrations.AlterField(
            model_name='otherpayment',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_payment', to='users.tenant', verbose_name='Tenant'),
        ),
    ]
