# Generated by Django 4.0.5 on 2022-09-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverification'),
        ('payment', '0003_alter_otherpayment_date_alter_otherpayment_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpayment',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_payment', to='users.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='users.tenant'),
        ),
    ]
